image: tiangolo/docker-with-compose
services:
  - docker:dind

stages:
  - lint
  - build
  - test

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

.lint-setup: &lint-setup
  stage: lint
  needs: []
  image: python:3.9
  services: []
  tags:
    - docker

Lint Python:
  <<: *lint-setup
  before_script:
    - pip install flake8
  script:
    - cd backend
    - flake8 --version
    - flake8 --max-line-length=100 src

Build Backend:
  stage: build
  needs: []
  tags:
    - docker
  # we do this since we cant copy the .env file into the our CI
  # so we make a dummy .env file
  before_script:
    - echo TMDB_API_KEY="dummy" >> backend/.env
  script:
    - echo "Building backend service..."
    - docker-compose up --build -d backend
  # remove .env so it doesnt stay as an artifact
  after_script:
    - rm backend/.env

Build Frontend:
  stage: build
  needs: []
  tags:
    - docker
  script:
    - echo "Building frontend service..."
    - docker-compose up --build -d frontend

Build Search:
  stage: build
  needs: []
  tags:
    - docker
  script:
    - echo "Building search service..."
    - docker-compose up --build -d search


