version: '3'
services:
    frontend:
        build: ./frontend
        container_name: svelte
        ports:
            - 5000:5000
            - 35729:35729
        volumes:
            - ./frontend/:/app/frontend
            - app/frontend/node_modules
        links:
            - backend
    backend:
        build: ./backend
        container_name: fastapi
        ports:
            - 1337:1337
        volumes:
            - ./backend/:/app/backend
        depends_on: ["search"]
    search:
        image: getmeili/meilisearch:latest
        container_name: meilisearch
        ports:
            - 7700:7700