version: '3'
services:
    api:
        build: .
        container_name: api
        ports:
            - 1337:1337
        volumes:
            -   ./app/:/app/app
    search:
        image: getmeili/meilisearch:latest
        container_name: meilisearch
        ports:
            - 7700:7700